<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor :
 * POGOProtos/Settings/Master/Item/ExperienceBoostAttributes.proto
 */


namespace POGOProtos\Settings\Master\Item;

/**
 * Protobuf message : POGOProtos.Settings.Master.Item.ExperienceBoostAttributes
 */
class ExperienceBoostAttributes extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * xp_multiplier optional float = 1
     *
     * @var float
     */
    protected $xp_multiplier = null;

    /**
     * boost_duration_ms optional int32 = 2
     *
     * @var int
     */
    protected $boost_duration_ms = null;

    /**
     * Check if 'xp_multiplier' has a value
     *
     * @return bool
     */
    public function hasXpMultiplier()
    {
        return $this->xp_multiplier !== null;
    }

    /**
     * Get 'xp_multiplier' value
     *
     * @return float
     */
    public function getXpMultiplier()
    {
        return $this->xp_multiplier;
    }

    /**
     * Set 'xp_multiplier' value
     *
     * @param float $value
     */
    public function setXpMultiplier($value = null)
    {
        $this->xp_multiplier = $value;
    }

    /**
     * Check if 'boost_duration_ms' has a value
     *
     * @return bool
     */
    public function hasBoostDurationMs()
    {
        return $this->boost_duration_ms !== null;
    }

    /**
     * Get 'boost_duration_ms' value
     *
     * @return int
     */
    public function getBoostDurationMs()
    {
        return $this->boost_duration_ms;
    }

    /**
     * Set 'boost_duration_ms' value
     *
     * @param int $value
     */
    public function setBoostDurationMs($value = null)
    {
        $this->boost_duration_ms = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'xp_multiplier' => null,
            'boost_duration_ms' => null
        ], $values);

        $message->setXpMultiplier($values['xp_multiplier']);
        $message->setBoostDurationMs($values['boost_duration_ms']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'ExperienceBoostAttributes',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'xp_multiplier',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_FLOAT(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'boost_duration_ms',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->xp_multiplier !== null) {
            $writer->writeVarint($stream, 13);
            $writer->writeFloat($stream, $this->xp_multiplier);
        }

        if ($this->boost_duration_ms !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->boost_duration_ms);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 2);

                $this->xp_multiplier = $reader->readFloat($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->boost_duration_ms = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->xp_multiplier !== null) {
            $size += 1;
            $size += 4;
        }

        if ($this->boost_duration_ms !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->boost_duration_ms);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->xp_multiplier = null;
        $this->boost_duration_ms = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \POGOProtos\Settings\Master\Item\ExperienceBoostAttributes) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->xp_multiplier = ($message->xp_multiplier !== null) ? $message->xp_multiplier : $this->xp_multiplier;
        $this->boost_duration_ms = ($message->boost_duration_ms !== null) ? $message->boost_duration_ms : $this->boost_duration_ms;
    }


}

