<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : POGOProtos/Settings/Master/FormSettings.proto
 */


namespace POGOProtos\Settings\Master\FormSettings;

/**
 * Protobuf message : POGOProtos.Settings.Master.FormSettings.Form
 */
class Form extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * form optional enum = 1
     *
     * @var \POGOProtos\Enums\Form
     */
    protected $form = null;

    /**
     * asset_bundle_value optional int32 = 2
     *
     * @var int
     */
    protected $asset_bundle_value = null;

    /**
     * Check if 'form' has a value
     *
     * @return bool
     */
    public function hasForm()
    {
        return $this->form !== null;
    }

    /**
     * Get 'form' value
     *
     * @return \POGOProtos\Enums\Form
     */
    public function getForm()
    {
        return $this->form;
    }

    /**
     * Set 'form' value
     *
     * @param \POGOProtos\Enums\Form $value
     */
    public function setForm(\POGOProtos\Enums\Form $value = null)
    {
        $this->form = $value;
    }

    /**
     * Check if 'asset_bundle_value' has a value
     *
     * @return bool
     */
    public function hasAssetBundleValue()
    {
        return $this->asset_bundle_value !== null;
    }

    /**
     * Get 'asset_bundle_value' value
     *
     * @return int
     */
    public function getAssetBundleValue()
    {
        return $this->asset_bundle_value;
    }

    /**
     * Set 'asset_bundle_value' value
     *
     * @param int $value
     */
    public function setAssetBundleValue($value = null)
    {
        $this->asset_bundle_value = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'form' => null,
            'asset_bundle_value' => null
        ], $values);

        $message->setForm($values['form']);
        $message->setAssetBundleValue($values['asset_bundle_value']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'Form',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'form',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_ENUM(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.POGOProtos.Enums.Form'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'asset_bundle_value',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->form !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->form->value());
        }

        if ($this->asset_bundle_value !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->asset_bundle_value);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 14);

                $this->form = \POGOProtos\Enums\Form::valueOf($reader->readVarint($stream));

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->asset_bundle_value = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->form !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->form->value());
        }

        if ($this->asset_bundle_value !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->asset_bundle_value);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->form = null;
        $this->asset_bundle_value = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \POGOProtos\Settings\Master\FormSettings\Form) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->form = ($message->form !== null) ? $message->form : $this->form;
        $this->asset_bundle_value = ($message->asset_bundle_value !== null) ? $message->asset_bundle_value : $this->asset_bundle_value;
    }


}

