<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : POGOProtos/Data/Raid/PlayerRaidInfo.proto
 */


namespace POGOProtos\Data\Raid;

/**
 * Protobuf message : POGOProtos.Data.Raid.PlayerRaidInfo
 */
class PlayerRaidInfo extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * total_completed_raids optional int32 = 3
     *
     * @var int
     */
    protected $total_completed_raids = null;

    /**
     * total_completed_legendary_raids optional int32 = 4
     *
     * @var int
     */
    protected $total_completed_legendary_raids = null;

    /**
     * raids repeated message = 5
     *
     * @var \Protobuf\Collection<\POGOProtos\Data\Raid\Raid>
     */
    protected $raids = null;

    /**
     * Check if 'total_completed_raids' has a value
     *
     * @return bool
     */
    public function hasTotalCompletedRaids()
    {
        return $this->total_completed_raids !== null;
    }

    /**
     * Get 'total_completed_raids' value
     *
     * @return int
     */
    public function getTotalCompletedRaids()
    {
        return $this->total_completed_raids;
    }

    /**
     * Set 'total_completed_raids' value
     *
     * @param int $value
     */
    public function setTotalCompletedRaids($value = null)
    {
        $this->total_completed_raids = $value;
    }

    /**
     * Check if 'total_completed_legendary_raids' has a value
     *
     * @return bool
     */
    public function hasTotalCompletedLegendaryRaids()
    {
        return $this->total_completed_legendary_raids !== null;
    }

    /**
     * Get 'total_completed_legendary_raids' value
     *
     * @return int
     */
    public function getTotalCompletedLegendaryRaids()
    {
        return $this->total_completed_legendary_raids;
    }

    /**
     * Set 'total_completed_legendary_raids' value
     *
     * @param int $value
     */
    public function setTotalCompletedLegendaryRaids($value = null)
    {
        $this->total_completed_legendary_raids = $value;
    }

    /**
     * Check if 'raids' has a value
     *
     * @return bool
     */
    public function hasRaidsList()
    {
        return $this->raids !== null;
    }

    /**
     * Get 'raids' value
     *
     * @return \Protobuf\Collection<\POGOProtos\Data\Raid\Raid>
     */
    public function getRaidsList()
    {
        return $this->raids;
    }

    /**
     * Set 'raids' value
     *
     * @param \Protobuf\Collection<\POGOProtos\Data\Raid\Raid> $value
     */
    public function setRaidsList(\Protobuf\Collection $value = null)
    {
        $this->raids = $value;
    }

    /**
     * Add a new element to 'raids'
     *
     * @param \POGOProtos\Data\Raid\Raid $value
     */
    public function addRaids(\POGOProtos\Data\Raid\Raid $value)
    {
        if ($this->raids === null) {
            $this->raids = new \Protobuf\MessageCollection();
        }

        $this->raids->add($value);
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'total_completed_raids' => null,
            'total_completed_legendary_raids' => null,
            'raids' => []
        ], $values);

        $message->setTotalCompletedRaids($values['total_completed_raids']);
        $message->setTotalCompletedLegendaryRaids($values['total_completed_legendary_raids']);

        foreach ($values['raids'] as $item) {
            $message->addRaids($item);
        }

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'PlayerRaidInfo',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'total_completed_raids',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'total_completed_legendary_raids',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'raids',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REPEATED(),
                    'type_name' => '.POGOProtos.Data.Raid.Raid'
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->total_completed_raids !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeVarint($stream, $this->total_completed_raids);
        }

        if ($this->total_completed_legendary_raids !== null) {
            $writer->writeVarint($stream, 32);
            $writer->writeVarint($stream, $this->total_completed_legendary_raids);
        }

        if ($this->raids !== null) {
            foreach ($this->raids as $val) {
                $writer->writeVarint($stream, 42);
                $writer->writeVarint($stream, $val->serializedSize($sizeContext));
                $val->writeTo($context);
            }
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->total_completed_raids = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->total_completed_legendary_raids = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \POGOProtos\Data\Raid\Raid();

                if ($this->raids === null) {
                    $this->raids = new \Protobuf\MessageCollection();
                }

                $this->raids->add($innerMessage);

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->total_completed_raids !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->total_completed_raids);
        }

        if ($this->total_completed_legendary_raids !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->total_completed_legendary_raids);
        }

        if ($this->raids !== null) {
            foreach ($this->raids as $val) {
                $innerSize = $val->serializedSize($context);

                $size += 1;
                $size += $innerSize;
                $size += $calculator->computeVarintSize($innerSize);
            }
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->total_completed_raids = null;
        $this->total_completed_legendary_raids = null;
        $this->raids = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \POGOProtos\Data\Raid\PlayerRaidInfo) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->total_completed_raids = ($message->total_completed_raids !== null) ? $message->total_completed_raids : $this->total_completed_raids;
        $this->total_completed_legendary_raids = ($message->total_completed_legendary_raids !== null) ? $message->total_completed_legendary_raids : $this->total_completed_legendary_raids;
        $this->raids = ($message->raids !== null) ? $message->raids : $this->raids;
    }


}

