<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : POGOProtos/Networking/Responses/EncounterResponse.proto
 */


namespace POGOProtos\Networking\Responses;

/**
 * Protobuf message : POGOProtos.Networking.Responses.EncounterResponse
 */
class EncounterResponse extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * wild_pokemon optional message = 1
     *
     * @var \POGOProtos\Map\Pokemon\WildPokemon
     */
    protected $wild_pokemon = null;

    /**
     * background optional enum = 2
     *
     * @var \POGOProtos\Networking\Responses\EncounterResponse\Background
     */
    protected $background = null;

    /**
     * status optional enum = 3
     *
     * @var \POGOProtos\Networking\Responses\EncounterResponse\Status
     */
    protected $status = null;

    /**
     * capture_probability optional message = 4
     *
     * @var \POGOProtos\Data\Capture\CaptureProbability
     */
    protected $capture_probability = null;

    /**
     * active_item optional enum = 5
     *
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected $active_item = null;

    /**
     * Check if 'wild_pokemon' has a value
     *
     * @return bool
     */
    public function hasWildPokemon()
    {
        return $this->wild_pokemon !== null;
    }

    /**
     * Get 'wild_pokemon' value
     *
     * @return \POGOProtos\Map\Pokemon\WildPokemon
     */
    public function getWildPokemon()
    {
        return $this->wild_pokemon;
    }

    /**
     * Set 'wild_pokemon' value
     *
     * @param \POGOProtos\Map\Pokemon\WildPokemon $value
     */
    public function setWildPokemon(\POGOProtos\Map\Pokemon\WildPokemon $value = null)
    {
        $this->wild_pokemon = $value;
    }

    /**
     * Check if 'background' has a value
     *
     * @return bool
     */
    public function hasBackground()
    {
        return $this->background !== null;
    }

    /**
     * Get 'background' value
     *
     * @return \POGOProtos\Networking\Responses\EncounterResponse\Background
     */
    public function getBackground()
    {
        return $this->background;
    }

    /**
     * Set 'background' value
     *
     * @param \POGOProtos\Networking\Responses\EncounterResponse\Background $value
     */
    public function setBackground(\POGOProtos\Networking\Responses\EncounterResponse\Background $value = null)
    {
        $this->background = $value;
    }

    /**
     * Check if 'status' has a value
     *
     * @return bool
     */
    public function hasStatus()
    {
        return $this->status !== null;
    }

    /**
     * Get 'status' value
     *
     * @return \POGOProtos\Networking\Responses\EncounterResponse\Status
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set 'status' value
     *
     * @param \POGOProtos\Networking\Responses\EncounterResponse\Status $value
     */
    public function setStatus(\POGOProtos\Networking\Responses\EncounterResponse\Status $value = null)
    {
        $this->status = $value;
    }

    /**
     * Check if 'capture_probability' has a value
     *
     * @return bool
     */
    public function hasCaptureProbability()
    {
        return $this->capture_probability !== null;
    }

    /**
     * Get 'capture_probability' value
     *
     * @return \POGOProtos\Data\Capture\CaptureProbability
     */
    public function getCaptureProbability()
    {
        return $this->capture_probability;
    }

    /**
     * Set 'capture_probability' value
     *
     * @param \POGOProtos\Data\Capture\CaptureProbability $value
     */
    public function setCaptureProbability(\POGOProtos\Data\Capture\CaptureProbability $value = null)
    {
        $this->capture_probability = $value;
    }

    /**
     * Check if 'active_item' has a value
     *
     * @return bool
     */
    public function hasActiveItem()
    {
        return $this->active_item !== null;
    }

    /**
     * Get 'active_item' value
     *
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public function getActiveItem()
    {
        return $this->active_item;
    }

    /**
     * Set 'active_item' value
     *
     * @param \POGOProtos\Inventory\Item\ItemId $value
     */
    public function setActiveItem(\POGOProtos\Inventory\Item\ItemId $value = null)
    {
        $this->active_item = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'wild_pokemon' => null,
            'background' => null,
            'status' => null,
            'capture_probability' => null,
            'active_item' => null
        ], $values);

        $message->setWildPokemon($values['wild_pokemon']);
        $message->setBackground($values['background']);
        $message->setStatus($values['status']);
        $message->setCaptureProbability($values['capture_probability']);
        $message->setActiveItem($values['active_item']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'EncounterResponse',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'wild_pokemon',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.POGOProtos.Map.Pokemon.WildPokemon'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'background',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_ENUM(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.POGOProtos.Networking.Responses.EncounterResponse.Background'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'status',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_ENUM(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.POGOProtos.Networking.Responses.EncounterResponse.Status'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'capture_probability',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.POGOProtos.Data.Capture.CaptureProbability'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'active_item',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_ENUM(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.POGOProtos.Inventory.Item.ItemId'
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->wild_pokemon !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeVarint($stream, $this->wild_pokemon->serializedSize($sizeContext));
            $this->wild_pokemon->writeTo($context);
        }

        if ($this->background !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->background->value());
        }

        if ($this->status !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeVarint($stream, $this->status->value());
        }

        if ($this->capture_probability !== null) {
            $writer->writeVarint($stream, 34);
            $writer->writeVarint($stream, $this->capture_probability->serializedSize($sizeContext));
            $this->capture_probability->writeTo($context);
        }

        if ($this->active_item !== null) {
            $writer->writeVarint($stream, 40);
            $writer->writeVarint($stream, $this->active_item->value());
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \POGOProtos\Map\Pokemon\WildPokemon();

                $this->wild_pokemon = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 14);

                $this->background = \POGOProtos\Networking\Responses\EncounterResponse\Background::valueOf($reader->readVarint($stream));

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 14);

                $this->status = \POGOProtos\Networking\Responses\EncounterResponse\Status::valueOf($reader->readVarint($stream));

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \POGOProtos\Data\Capture\CaptureProbability();

                $this->capture_probability = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 14);

                $this->active_item = \POGOProtos\Inventory\Item\ItemId::valueOf($reader->readVarint($stream));

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->wild_pokemon !== null) {
            $innerSize = $this->wild_pokemon->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->background !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->background->value());
        }

        if ($this->status !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->status->value());
        }

        if ($this->capture_probability !== null) {
            $innerSize = $this->capture_probability->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->active_item !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->active_item->value());
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->wild_pokemon = null;
        $this->background = null;
        $this->status = null;
        $this->capture_probability = null;
        $this->active_item = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \POGOProtos\Networking\Responses\EncounterResponse) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->wild_pokemon = ($message->wild_pokemon !== null) ? $message->wild_pokemon : $this->wild_pokemon;
        $this->background = ($message->background !== null) ? $message->background : $this->background;
        $this->status = ($message->status !== null) ? $message->status : $this->status;
        $this->capture_probability = ($message->capture_probability !== null) ? $message->capture_probability : $this->capture_probability;
        $this->active_item = ($message->active_item !== null) ? $message->active_item : $this->active_item;
    }


}

