<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/SetFavoritePokemonResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class SetFavoritePokemonResponse extends \Google\Protobuf\Internal\Message
{
    private $result = 0;

    public function getResult()
    {
        return $this->result;
    }

    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Networking\Responses\SetFavoritePokemonResponse_Result::class);
        $this->result = $var;
    }

}

class SetFavoritePokemonResponse_Result
{
    const UNSET = 0;
    const SUCCESS = 1;
    const ERROR_POKEMON_NOT_FOUND = 2;
    const ERROR_POKEMON_IS_EGG = 3;
}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0ab7020a40504f474f50726f746f732f4e6574776f726b696e672f526573" .
    "706f6e7365732f5365744661766f72697465506f6b656d6f6e526573706f" .
    "6e73652e70726f746f121f504f474f50726f746f732e4e6574776f726b69" .
    "6e672e526573706f6e73657322c9010a1a5365744661766f72697465506f" .
    "6b656d6f6e526573706f6e736512520a06726573756c7418012001280e32" .
    "422e504f474f50726f746f732e4e6574776f726b696e672e526573706f6e" .
    "7365732e5365744661766f72697465506f6b656d6f6e526573706f6e7365" .
    "2e526573756c7422570a06526573756c7412090a05554e5345541000120b" .
    "0a07535543434553531001121b0a174552524f525f504f4b454d4f4e5f4e" .
    "4f545f464f554e44100212180a144552524f525f504f4b454d4f4e5f4953" .
    "5f4547471003620670726f746f33"
));

