<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/MapCell.proto

namespace POGOProtos\Map;

require_once('POGOProtos/Map/SpawnPoint.pb.php');
require_once('POGOProtos/Map/Fort/FortData.pb.php');
require_once('POGOProtos/Map/Fort/FortSummary.pb.php');
require_once('POGOProtos/Map/Pokemon/NearbyPokemon.pb.php');
require_once('POGOProtos/Map/Pokemon/WildPokemon.pb.php');
require_once('POGOProtos/Map/Pokemon/MapPokemon.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class MapCell extends \Google\Protobuf\Internal\Message
{
    private $s2_cell_id = 0;
    private $current_timestamp_ms = 0;
    private $forts;
    private $spawn_points;
    private $deleted_objects;
    private $is_truncated_list = false;
    private $fort_summaries;
    private $decimated_spawn_points;
    private $wild_pokemons;
    private $catchable_pokemons;
    private $nearby_pokemons;

    public function getS2CellId()
    {
        return $this->s2_cell_id;
    }

    public function setS2CellId($var)
    {
        GPBUtil::checkUint64($var);
        $this->s2_cell_id = $var;
    }

    public function getCurrentTimestampMs()
    {
        return $this->current_timestamp_ms;
    }

    public function setCurrentTimestampMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->current_timestamp_ms = $var;
    }

    public function getForts()
    {
        return $this->forts;
    }

    public function setForts(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \POGOProtos\Map\Fort\FortData::class);
        $this->forts = $var;
    }

    public function getSpawnPoints()
    {
        return $this->spawn_points;
    }

    public function setSpawnPoints(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \POGOProtos\Map\SpawnPoint::class);
        $this->spawn_points = $var;
    }

    public function getDeletedObjects()
    {
        return $this->deleted_objects;
    }

    public function setDeletedObjects(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->deleted_objects = $var;
    }

    public function getIsTruncatedList()
    {
        return $this->is_truncated_list;
    }

    public function setIsTruncatedList($var)
    {
        GPBUtil::checkBool($var);
        $this->is_truncated_list = $var;
    }

    public function getFortSummaries()
    {
        return $this->fort_summaries;
    }

    public function setFortSummaries(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \POGOProtos\Map\Fort\FortSummary::class);
        $this->fort_summaries = $var;
    }

    public function getDecimatedSpawnPoints()
    {
        return $this->decimated_spawn_points;
    }

    public function setDecimatedSpawnPoints(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \POGOProtos\Map\SpawnPoint::class);
        $this->decimated_spawn_points = $var;
    }

    public function getWildPokemons()
    {
        return $this->wild_pokemons;
    }

    public function setWildPokemons(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \POGOProtos\Map\Pokemon\WildPokemon::class);
        $this->wild_pokemons = $var;
    }

    public function getCatchablePokemons()
    {
        return $this->catchable_pokemons;
    }

    public function setCatchablePokemons(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \POGOProtos\Map\Pokemon\MapPokemon::class);
        $this->catchable_pokemons = $var;
    }

    public function getNearbyPokemons()
    {
        return $this->nearby_pokemons;
    }

    public function setNearbyPokemons(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \POGOProtos\Map\Pokemon\NearbyPokemon::class);
        $this->nearby_pokemons = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0aa5060a1c504f474f50726f746f732f4d61702f4d617043656c6c2e7072" .
    "6f746f120e504f474f50726f746f732e4d61701a1f504f474f50726f746f" .
    "732f4d61702f537061776e506f696e742e70726f746f1a22504f474f5072" .
    "6f746f732f4d61702f466f72742f466f7274446174612e70726f746f1a25" .
    "504f474f50726f746f732f4d61702f466f72742f466f727453756d6d6172" .
    "792e70726f746f1a2a504f474f50726f746f732f4d61702f506f6b656d6f" .
    "6e2f4e6561726279506f6b656d6f6e2e70726f746f1a28504f474f50726f" .
    "746f732f4d61702f506f6b656d6f6e2f57696c64506f6b656d6f6e2e7072" .
    "6f746f1a27504f474f50726f746f732f4d61702f506f6b656d6f6e2f4d61" .
    "70506f6b656d6f6e2e70726f746f2281040a074d617043656c6c12120a0a" .
    "73325f63656c6c5f6964180120012804121c0a1463757272656e745f7469" .
    "6d657374616d705f6d73180220012803122c0a05666f7274731803200328" .
    "0b321d2e504f474f50726f746f732e4d61702e466f72742e466f72744461" .
    "746112300a0c737061776e5f706f696e747318042003280b321a2e504f47" .
    "4f50726f746f732e4d61702e537061776e506f696e7412170a0f64656c65" .
    "7465645f6f626a6563747318062003280912190a1169735f7472756e6361" .
    "7465645f6c69737418072001280812380a0e666f72745f73756d6d617269" .
    "657318082003280b32202e504f474f50726f746f732e4d61702e466f7274" .
    "2e466f727453756d6d617279123a0a16646563696d617465645f73706177" .
    "6e5f706f696e747318092003280b321a2e504f474f50726f746f732e4d61" .
    "702e537061776e506f696e74123a0a0d77696c645f706f6b656d6f6e7318" .
    "052003280b32232e504f474f50726f746f732e4d61702e506f6b656d6f6e" .
    "2e57696c64506f6b656d6f6e123e0a12636174636861626c655f706f6b65" .
    "6d6f6e73180a2003280b32222e504f474f50726f746f732e4d61702e506f" .
    "6b656d6f6e2e4d6170506f6b656d6f6e123e0a0f6e65617262795f706f6b" .
    "656d6f6e73180b2003280b32252e504f474f50726f746f732e4d61702e50" .
    "6f6b656d6f6e2e4e6561726279506f6b656d6f6e620670726f746f33"
));

