<?php
// Generated by https://github.com/jaspervdm/protoc-gen-php
namespace POGOProtos\Map\Fort {

  use Protobuf;
  use ProtobufIO;
  use ProtobufEnum;
  use ProtobufMessage;

  // enum POGOProtos.Map.Fort.FortType
  abstract class FortType extends ProtobufEnum {
    const GYM = 0;
    const CHECKPOINT = 1;

    public static $_values = array(
      0 => "GYM",
      1 => "CHECKPOINT",
    );

    public static function isValid($value) {
      return array_key_exists($value, self::$_values);
    }

    public static function toString($value) {
      checkArgument(is_int($value), 'value must be a integer');
      if (array_key_exists($value, self::$_values))
        return self::$_values[$value];
      return 'UNKNOWN';
    }
  }

}