<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : POGOProtos/Data/Badge/GymBadgeStats.proto
 */


namespace POGOProtos\Data\Badge;

/**
 * Protobuf message : POGOProtos.Data.Badge.GymBadgeStats
 */
class GymBadgeStats extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * total_time_defended_ms optional uint64 = 1
     *
     * @var int
     */
    protected $total_time_defended_ms = null;

    /**
     * num_battles_won optional uint32 = 2
     *
     * @var int
     */
    protected $num_battles_won = null;

    /**
     * num_battles_lost optional uint32 = 5
     *
     * @var int
     */
    protected $num_battles_lost = null;

    /**
     * num_berries_fed optional uint32 = 3
     *
     * @var int
     */
    protected $num_berries_fed = null;

    /**
     * num_deploys optional uint32 = 4
     *
     * @var int
     */
    protected $num_deploys = null;

    /**
     * Check if 'total_time_defended_ms' has a value
     *
     * @return bool
     */
    public function hasTotalTimeDefendedMs()
    {
        return $this->total_time_defended_ms !== null;
    }

    /**
     * Get 'total_time_defended_ms' value
     *
     * @return int
     */
    public function getTotalTimeDefendedMs()
    {
        return $this->total_time_defended_ms;
    }

    /**
     * Set 'total_time_defended_ms' value
     *
     * @param int $value
     */
    public function setTotalTimeDefendedMs($value = null)
    {
        $this->total_time_defended_ms = $value;
    }

    /**
     * Check if 'num_battles_won' has a value
     *
     * @return bool
     */
    public function hasNumBattlesWon()
    {
        return $this->num_battles_won !== null;
    }

    /**
     * Get 'num_battles_won' value
     *
     * @return int
     */
    public function getNumBattlesWon()
    {
        return $this->num_battles_won;
    }

    /**
     * Set 'num_battles_won' value
     *
     * @param int $value
     */
    public function setNumBattlesWon($value = null)
    {
        $this->num_battles_won = $value;
    }

    /**
     * Check if 'num_battles_lost' has a value
     *
     * @return bool
     */
    public function hasNumBattlesLost()
    {
        return $this->num_battles_lost !== null;
    }

    /**
     * Get 'num_battles_lost' value
     *
     * @return int
     */
    public function getNumBattlesLost()
    {
        return $this->num_battles_lost;
    }

    /**
     * Set 'num_battles_lost' value
     *
     * @param int $value
     */
    public function setNumBattlesLost($value = null)
    {
        $this->num_battles_lost = $value;
    }

    /**
     * Check if 'num_berries_fed' has a value
     *
     * @return bool
     */
    public function hasNumBerriesFed()
    {
        return $this->num_berries_fed !== null;
    }

    /**
     * Get 'num_berries_fed' value
     *
     * @return int
     */
    public function getNumBerriesFed()
    {
        return $this->num_berries_fed;
    }

    /**
     * Set 'num_berries_fed' value
     *
     * @param int $value
     */
    public function setNumBerriesFed($value = null)
    {
        $this->num_berries_fed = $value;
    }

    /**
     * Check if 'num_deploys' has a value
     *
     * @return bool
     */
    public function hasNumDeploys()
    {
        return $this->num_deploys !== null;
    }

    /**
     * Get 'num_deploys' value
     *
     * @return int
     */
    public function getNumDeploys()
    {
        return $this->num_deploys;
    }

    /**
     * Set 'num_deploys' value
     *
     * @param int $value
     */
    public function setNumDeploys($value = null)
    {
        $this->num_deploys = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'total_time_defended_ms' => null,
            'num_battles_won' => null,
            'num_battles_lost' => null,
            'num_berries_fed' => null,
            'num_deploys' => null
        ], $values);

        $message->setTotalTimeDefendedMs($values['total_time_defended_ms']);
        $message->setNumBattlesWon($values['num_battles_won']);
        $message->setNumBattlesLost($values['num_battles_lost']);
        $message->setNumBerriesFed($values['num_berries_fed']);
        $message->setNumDeploys($values['num_deploys']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'GymBadgeStats',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'total_time_defended_ms',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'num_battles_won',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'num_battles_lost',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'num_berries_fed',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'num_deploys',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->total_time_defended_ms !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->total_time_defended_ms);
        }

        if ($this->num_battles_won !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->num_battles_won);
        }

        if ($this->num_battles_lost !== null) {
            $writer->writeVarint($stream, 40);
            $writer->writeVarint($stream, $this->num_battles_lost);
        }

        if ($this->num_berries_fed !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeVarint($stream, $this->num_berries_fed);
        }

        if ($this->num_deploys !== null) {
            $writer->writeVarint($stream, 32);
            $writer->writeVarint($stream, $this->num_deploys);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 4);

                $this->total_time_defended_ms = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->num_battles_won = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->num_battles_lost = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->num_berries_fed = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->num_deploys = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->total_time_defended_ms !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->total_time_defended_ms);
        }

        if ($this->num_battles_won !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->num_battles_won);
        }

        if ($this->num_battles_lost !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->num_battles_lost);
        }

        if ($this->num_berries_fed !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->num_berries_fed);
        }

        if ($this->num_deploys !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->num_deploys);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->total_time_defended_ms = null;
        $this->num_battles_won = null;
        $this->num_battles_lost = null;
        $this->num_berries_fed = null;
        $this->num_deploys = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \POGOProtos\Data\Badge\GymBadgeStats) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->total_time_defended_ms = ($message->total_time_defended_ms !== null) ? $message->total_time_defended_ms : $this->total_time_defended_ms;
        $this->num_battles_won = ($message->num_battles_won !== null) ? $message->num_battles_won : $this->num_battles_won;
        $this->num_battles_lost = ($message->num_battles_lost !== null) ? $message->num_battles_lost : $this->num_battles_lost;
        $this->num_berries_fed = ($message->num_berries_fed !== null) ? $message->num_berries_fed : $this->num_berries_fed;
        $this->num_deploys = ($message->num_deploys !== null) ? $message->num_deploys : $this->num_deploys;
    }


}

