<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : POGOProtos/Enums/ActivityType.proto
 */


namespace POGOProtos\Enums;

/**
 * Protobuf enum : POGOProtos.Enums.ActivityType
 */
class ActivityType extends \Protobuf\Enum
{

    /**
     * ACTIVITY_UNKNOWN = 0
     */
    const ACTIVITY_UNKNOWN_VALUE = 0;

    /**
     * ACTIVITY_CATCH_POKEMON = 1
     */
    const ACTIVITY_CATCH_POKEMON_VALUE = 1;

    /**
     * ACTIVITY_CATCH_LEGEND_POKEMON = 2
     */
    const ACTIVITY_CATCH_LEGEND_POKEMON_VALUE = 2;

    /**
     * ACTIVITY_FLEE_POKEMON = 3
     */
    const ACTIVITY_FLEE_POKEMON_VALUE = 3;

    /**
     * ACTIVITY_DEFEAT_FORT = 4
     */
    const ACTIVITY_DEFEAT_FORT_VALUE = 4;

    /**
     * ACTIVITY_EVOLVE_POKEMON = 5
     */
    const ACTIVITY_EVOLVE_POKEMON_VALUE = 5;

    /**
     * ACTIVITY_HATCH_EGG = 6
     */
    const ACTIVITY_HATCH_EGG_VALUE = 6;

    /**
     * ACTIVITY_WALK_KM = 7
     */
    const ACTIVITY_WALK_KM_VALUE = 7;

    /**
     * ACTIVITY_POKEDEX_ENTRY_NEW = 8
     */
    const ACTIVITY_POKEDEX_ENTRY_NEW_VALUE = 8;

    /**
     * ACTIVITY_CATCH_FIRST_THROW = 9
     */
    const ACTIVITY_CATCH_FIRST_THROW_VALUE = 9;

    /**
     * ACTIVITY_CATCH_NICE_THROW = 10
     */
    const ACTIVITY_CATCH_NICE_THROW_VALUE = 10;

    /**
     * ACTIVITY_CATCH_GREAT_THROW = 11
     */
    const ACTIVITY_CATCH_GREAT_THROW_VALUE = 11;

    /**
     * ACTIVITY_CATCH_EXCELLENT_THROW = 12
     */
    const ACTIVITY_CATCH_EXCELLENT_THROW_VALUE = 12;

    /**
     * ACTIVITY_CATCH_CURVEBALL = 13
     */
    const ACTIVITY_CATCH_CURVEBALL_VALUE = 13;

    /**
     * ACTIVITY_CATCH_FIRST_CATCH_OF_DAY = 14
     */
    const ACTIVITY_CATCH_FIRST_CATCH_OF_DAY_VALUE = 14;

    /**
     * ACTIVITY_CATCH_MILESTONE = 15
     */
    const ACTIVITY_CATCH_MILESTONE_VALUE = 15;

    /**
     * ACTIVITY_TRAIN_POKEMON = 16
     */
    const ACTIVITY_TRAIN_POKEMON_VALUE = 16;

    /**
     * ACTIVITY_SEARCH_FORT = 17
     */
    const ACTIVITY_SEARCH_FORT_VALUE = 17;

    /**
     * ACTIVITY_RELEASE_POKEMON = 18
     */
    const ACTIVITY_RELEASE_POKEMON_VALUE = 18;

    /**
     * ACTIVITY_HATCH_EGG_SMALL_BONUS = 19
     */
    const ACTIVITY_HATCH_EGG_SMALL_BONUS_VALUE = 19;

    /**
     * ACTIVITY_HATCH_EGG_MEDIUM_BONUS = 20
     */
    const ACTIVITY_HATCH_EGG_MEDIUM_BONUS_VALUE = 20;

    /**
     * ACTIVITY_HATCH_EGG_LARGE_BONUS = 21
     */
    const ACTIVITY_HATCH_EGG_LARGE_BONUS_VALUE = 21;

    /**
     * ACTIVITY_DEFEAT_GYM_DEFENDER = 22
     */
    const ACTIVITY_DEFEAT_GYM_DEFENDER_VALUE = 22;

    /**
     * ACTIVITY_DEFEAT_GYM_LEADER = 23
     */
    const ACTIVITY_DEFEAT_GYM_LEADER_VALUE = 23;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_UNKNOWN = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_CATCH_POKEMON = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_CATCH_LEGEND_POKEMON = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_FLEE_POKEMON = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_DEFEAT_FORT = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_EVOLVE_POKEMON = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_HATCH_EGG = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_WALK_KM = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_POKEDEX_ENTRY_NEW = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_CATCH_FIRST_THROW = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_CATCH_NICE_THROW = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_CATCH_GREAT_THROW = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_CATCH_EXCELLENT_THROW = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_CATCH_CURVEBALL = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_CATCH_FIRST_CATCH_OF_DAY = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_CATCH_MILESTONE = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_TRAIN_POKEMON = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_SEARCH_FORT = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_RELEASE_POKEMON = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_HATCH_EGG_SMALL_BONUS = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_HATCH_EGG_MEDIUM_BONUS = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_HATCH_EGG_LARGE_BONUS = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_DEFEAT_GYM_DEFENDER = null;

    /**
     * @var \POGOProtos\Enums\ActivityType
     */
    protected static $ACTIVITY_DEFEAT_GYM_LEADER = null;

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_UNKNOWN()
    {
        if (self::$ACTIVITY_UNKNOWN !== null) {
            return self::$ACTIVITY_UNKNOWN;
        }

        return self::$ACTIVITY_UNKNOWN = new self('ACTIVITY_UNKNOWN', self::ACTIVITY_UNKNOWN_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_CATCH_POKEMON()
    {
        if (self::$ACTIVITY_CATCH_POKEMON !== null) {
            return self::$ACTIVITY_CATCH_POKEMON;
        }

        return self::$ACTIVITY_CATCH_POKEMON = new self('ACTIVITY_CATCH_POKEMON', self::ACTIVITY_CATCH_POKEMON_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_CATCH_LEGEND_POKEMON()
    {
        if (self::$ACTIVITY_CATCH_LEGEND_POKEMON !== null) {
            return self::$ACTIVITY_CATCH_LEGEND_POKEMON;
        }

        return self::$ACTIVITY_CATCH_LEGEND_POKEMON = new self('ACTIVITY_CATCH_LEGEND_POKEMON', self::ACTIVITY_CATCH_LEGEND_POKEMON_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_FLEE_POKEMON()
    {
        if (self::$ACTIVITY_FLEE_POKEMON !== null) {
            return self::$ACTIVITY_FLEE_POKEMON;
        }

        return self::$ACTIVITY_FLEE_POKEMON = new self('ACTIVITY_FLEE_POKEMON', self::ACTIVITY_FLEE_POKEMON_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_DEFEAT_FORT()
    {
        if (self::$ACTIVITY_DEFEAT_FORT !== null) {
            return self::$ACTIVITY_DEFEAT_FORT;
        }

        return self::$ACTIVITY_DEFEAT_FORT = new self('ACTIVITY_DEFEAT_FORT', self::ACTIVITY_DEFEAT_FORT_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_EVOLVE_POKEMON()
    {
        if (self::$ACTIVITY_EVOLVE_POKEMON !== null) {
            return self::$ACTIVITY_EVOLVE_POKEMON;
        }

        return self::$ACTIVITY_EVOLVE_POKEMON = new self('ACTIVITY_EVOLVE_POKEMON', self::ACTIVITY_EVOLVE_POKEMON_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_HATCH_EGG()
    {
        if (self::$ACTIVITY_HATCH_EGG !== null) {
            return self::$ACTIVITY_HATCH_EGG;
        }

        return self::$ACTIVITY_HATCH_EGG = new self('ACTIVITY_HATCH_EGG', self::ACTIVITY_HATCH_EGG_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_WALK_KM()
    {
        if (self::$ACTIVITY_WALK_KM !== null) {
            return self::$ACTIVITY_WALK_KM;
        }

        return self::$ACTIVITY_WALK_KM = new self('ACTIVITY_WALK_KM', self::ACTIVITY_WALK_KM_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_POKEDEX_ENTRY_NEW()
    {
        if (self::$ACTIVITY_POKEDEX_ENTRY_NEW !== null) {
            return self::$ACTIVITY_POKEDEX_ENTRY_NEW;
        }

        return self::$ACTIVITY_POKEDEX_ENTRY_NEW = new self('ACTIVITY_POKEDEX_ENTRY_NEW', self::ACTIVITY_POKEDEX_ENTRY_NEW_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_CATCH_FIRST_THROW()
    {
        if (self::$ACTIVITY_CATCH_FIRST_THROW !== null) {
            return self::$ACTIVITY_CATCH_FIRST_THROW;
        }

        return self::$ACTIVITY_CATCH_FIRST_THROW = new self('ACTIVITY_CATCH_FIRST_THROW', self::ACTIVITY_CATCH_FIRST_THROW_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_CATCH_NICE_THROW()
    {
        if (self::$ACTIVITY_CATCH_NICE_THROW !== null) {
            return self::$ACTIVITY_CATCH_NICE_THROW;
        }

        return self::$ACTIVITY_CATCH_NICE_THROW = new self('ACTIVITY_CATCH_NICE_THROW', self::ACTIVITY_CATCH_NICE_THROW_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_CATCH_GREAT_THROW()
    {
        if (self::$ACTIVITY_CATCH_GREAT_THROW !== null) {
            return self::$ACTIVITY_CATCH_GREAT_THROW;
        }

        return self::$ACTIVITY_CATCH_GREAT_THROW = new self('ACTIVITY_CATCH_GREAT_THROW', self::ACTIVITY_CATCH_GREAT_THROW_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_CATCH_EXCELLENT_THROW()
    {
        if (self::$ACTIVITY_CATCH_EXCELLENT_THROW !== null) {
            return self::$ACTIVITY_CATCH_EXCELLENT_THROW;
        }

        return self::$ACTIVITY_CATCH_EXCELLENT_THROW = new self('ACTIVITY_CATCH_EXCELLENT_THROW', self::ACTIVITY_CATCH_EXCELLENT_THROW_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_CATCH_CURVEBALL()
    {
        if (self::$ACTIVITY_CATCH_CURVEBALL !== null) {
            return self::$ACTIVITY_CATCH_CURVEBALL;
        }

        return self::$ACTIVITY_CATCH_CURVEBALL = new self('ACTIVITY_CATCH_CURVEBALL', self::ACTIVITY_CATCH_CURVEBALL_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_CATCH_FIRST_CATCH_OF_DAY()
    {
        if (self::$ACTIVITY_CATCH_FIRST_CATCH_OF_DAY !== null) {
            return self::$ACTIVITY_CATCH_FIRST_CATCH_OF_DAY;
        }

        return self::$ACTIVITY_CATCH_FIRST_CATCH_OF_DAY = new self('ACTIVITY_CATCH_FIRST_CATCH_OF_DAY', self::ACTIVITY_CATCH_FIRST_CATCH_OF_DAY_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_CATCH_MILESTONE()
    {
        if (self::$ACTIVITY_CATCH_MILESTONE !== null) {
            return self::$ACTIVITY_CATCH_MILESTONE;
        }

        return self::$ACTIVITY_CATCH_MILESTONE = new self('ACTIVITY_CATCH_MILESTONE', self::ACTIVITY_CATCH_MILESTONE_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_TRAIN_POKEMON()
    {
        if (self::$ACTIVITY_TRAIN_POKEMON !== null) {
            return self::$ACTIVITY_TRAIN_POKEMON;
        }

        return self::$ACTIVITY_TRAIN_POKEMON = new self('ACTIVITY_TRAIN_POKEMON', self::ACTIVITY_TRAIN_POKEMON_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_SEARCH_FORT()
    {
        if (self::$ACTIVITY_SEARCH_FORT !== null) {
            return self::$ACTIVITY_SEARCH_FORT;
        }

        return self::$ACTIVITY_SEARCH_FORT = new self('ACTIVITY_SEARCH_FORT', self::ACTIVITY_SEARCH_FORT_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_RELEASE_POKEMON()
    {
        if (self::$ACTIVITY_RELEASE_POKEMON !== null) {
            return self::$ACTIVITY_RELEASE_POKEMON;
        }

        return self::$ACTIVITY_RELEASE_POKEMON = new self('ACTIVITY_RELEASE_POKEMON', self::ACTIVITY_RELEASE_POKEMON_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_HATCH_EGG_SMALL_BONUS()
    {
        if (self::$ACTIVITY_HATCH_EGG_SMALL_BONUS !== null) {
            return self::$ACTIVITY_HATCH_EGG_SMALL_BONUS;
        }

        return self::$ACTIVITY_HATCH_EGG_SMALL_BONUS = new self('ACTIVITY_HATCH_EGG_SMALL_BONUS', self::ACTIVITY_HATCH_EGG_SMALL_BONUS_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_HATCH_EGG_MEDIUM_BONUS()
    {
        if (self::$ACTIVITY_HATCH_EGG_MEDIUM_BONUS !== null) {
            return self::$ACTIVITY_HATCH_EGG_MEDIUM_BONUS;
        }

        return self::$ACTIVITY_HATCH_EGG_MEDIUM_BONUS = new self('ACTIVITY_HATCH_EGG_MEDIUM_BONUS', self::ACTIVITY_HATCH_EGG_MEDIUM_BONUS_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_HATCH_EGG_LARGE_BONUS()
    {
        if (self::$ACTIVITY_HATCH_EGG_LARGE_BONUS !== null) {
            return self::$ACTIVITY_HATCH_EGG_LARGE_BONUS;
        }

        return self::$ACTIVITY_HATCH_EGG_LARGE_BONUS = new self('ACTIVITY_HATCH_EGG_LARGE_BONUS', self::ACTIVITY_HATCH_EGG_LARGE_BONUS_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_DEFEAT_GYM_DEFENDER()
    {
        if (self::$ACTIVITY_DEFEAT_GYM_DEFENDER !== null) {
            return self::$ACTIVITY_DEFEAT_GYM_DEFENDER;
        }

        return self::$ACTIVITY_DEFEAT_GYM_DEFENDER = new self('ACTIVITY_DEFEAT_GYM_DEFENDER', self::ACTIVITY_DEFEAT_GYM_DEFENDER_VALUE);
    }

    /**
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function ACTIVITY_DEFEAT_GYM_LEADER()
    {
        if (self::$ACTIVITY_DEFEAT_GYM_LEADER !== null) {
            return self::$ACTIVITY_DEFEAT_GYM_LEADER;
        }

        return self::$ACTIVITY_DEFEAT_GYM_LEADER = new self('ACTIVITY_DEFEAT_GYM_LEADER', self::ACTIVITY_DEFEAT_GYM_LEADER_VALUE);
    }

    /**
     * @param int $value
     * @return \POGOProtos\Enums\ActivityType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::ACTIVITY_UNKNOWN();
            case 1: return self::ACTIVITY_CATCH_POKEMON();
            case 2: return self::ACTIVITY_CATCH_LEGEND_POKEMON();
            case 3: return self::ACTIVITY_FLEE_POKEMON();
            case 4: return self::ACTIVITY_DEFEAT_FORT();
            case 5: return self::ACTIVITY_EVOLVE_POKEMON();
            case 6: return self::ACTIVITY_HATCH_EGG();
            case 7: return self::ACTIVITY_WALK_KM();
            case 8: return self::ACTIVITY_POKEDEX_ENTRY_NEW();
            case 9: return self::ACTIVITY_CATCH_FIRST_THROW();
            case 10: return self::ACTIVITY_CATCH_NICE_THROW();
            case 11: return self::ACTIVITY_CATCH_GREAT_THROW();
            case 12: return self::ACTIVITY_CATCH_EXCELLENT_THROW();
            case 13: return self::ACTIVITY_CATCH_CURVEBALL();
            case 14: return self::ACTIVITY_CATCH_FIRST_CATCH_OF_DAY();
            case 15: return self::ACTIVITY_CATCH_MILESTONE();
            case 16: return self::ACTIVITY_TRAIN_POKEMON();
            case 17: return self::ACTIVITY_SEARCH_FORT();
            case 18: return self::ACTIVITY_RELEASE_POKEMON();
            case 19: return self::ACTIVITY_HATCH_EGG_SMALL_BONUS();
            case 20: return self::ACTIVITY_HATCH_EGG_MEDIUM_BONUS();
            case 21: return self::ACTIVITY_HATCH_EGG_LARGE_BONUS();
            case 22: return self::ACTIVITY_DEFEAT_GYM_DEFENDER();
            case 23: return self::ACTIVITY_DEFEAT_GYM_LEADER();
            default: return null;
        }
    }


}

