<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/Gender.proto

namespace POGOProtos\Enums;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Gender
{
    const MALE = 0;
    const FEMALE = 1;
}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0a590a1d504f474f50726f746f732f456e756d732f47656e6465722e7072" .
    "6f746f1210504f474f50726f746f732e456e756d732a1e0a0647656e6465" .
    "7212080a044d414c451000120a0a0646454d414c451001620670726f746f" .
    "33"
));

