<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/TutorialState.proto

namespace POGOProtos\Enums;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class TutorialState
{
    const LEGAL_SCREEN = 0;
    const AVATAR_SELECTION = 1;
    const ACCOUNT_CREATION = 2;
    const POKEMON_CAPTURE = 3;
    const NAME_SELECTION = 4;
    const POKEMON_BERRY = 5;
    const USE_ITEM = 6;
    const FIRST_TIME_EXPERIENCE_COMPLETE = 7;
    const POKESTOP_TUTORIAL = 8;
    const GYM_TUTORIAL = 9;
}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0aa7020a24504f474f50726f746f732f456e756d732f5475746f7269616c" .
    "53746174652e70726f746f1210504f474f50726f746f732e456e756d732a" .
    "e4010a0d5475746f7269616c537461746512100a0c4c4547414c5f534352" .
    "45454e100012140a104156415441525f53454c454354494f4e100112140a" .
    "104143434f554e545f4352454154494f4e100212130a0f504f4b454d4f4e" .
    "5f43415054555245100312120a0e4e414d455f53454c454354494f4e1004" .
    "12110a0d504f4b454d4f4e5f42455252591005120c0a085553455f495445" .
    "4d100612220a1e46495253545f54494d455f455850455249454e43455f43" .
    "4f4d504c455445100712150a11504f4b4553544f505f5455544f5249414c" .
    "100812100a0c47594d5f5455544f5249414c1009620670726f746f33"
));

