<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/DownloadItemTemplatesMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class DownloadItemTemplatesMessage extends \Google\Protobuf\Internal\Message
{

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0a9d010a4a504f474f50726f746f732f4e6574776f726b696e672f526571" .
    "75657374732f4d657373616765732f446f776e6c6f61644974656d54656d" .
    "706c617465734d6573736167652e70726f746f1227504f474f50726f746f" .
    "732e4e6574776f726b696e672e52657175657374732e4d65737361676573" .
    "221e0a1c446f776e6c6f61644974656d54656d706c617465734d65737361" .
    "6765620670726f746f33"
));

