<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/GetBuddyWalked.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class GetBuddyWalkedMessage extends \Google\Protobuf\Internal\Message
{

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0a88010a3c504f474f50726f746f732f4e6574776f726b696e672f526571" .
    "75657374732f4d657373616765732f476574427564647957616c6b65642e" .
    "70726f746f1227504f474f50726f746f732e4e6574776f726b696e672e52" .
    "657175657374732e4d6573736167657322170a1547657442756464795761" .
    "6c6b65644d657373616765620670726f746f33"
));

