<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor :
 * POGOProtos/Networking/Requests/Messages/GymGetInfoMessage.proto
 */


namespace POGOProtos\Networking\Requests\Messages;

/**
 * Protobuf message : POGOProtos.Networking.Requests.Messages.GymGetInfoMessage
 */
class GymGetInfoMessage extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * gym_id optional string = 1
     *
     * @var string
     */
    protected $gym_id = null;

    /**
     * player_lat_degrees optional double = 2
     *
     * @var float
     */
    protected $player_lat_degrees = null;

    /**
     * player_lng_degrees optional double = 3
     *
     * @var float
     */
    protected $player_lng_degrees = null;

    /**
     * gym_lat_degrees optional double = 4
     *
     * @var float
     */
    protected $gym_lat_degrees = null;

    /**
     * gym_lng_degrees optional double = 5
     *
     * @var float
     */
    protected $gym_lng_degrees = null;

    /**
     * Check if 'gym_id' has a value
     *
     * @return bool
     */
    public function hasGymId()
    {
        return $this->gym_id !== null;
    }

    /**
     * Get 'gym_id' value
     *
     * @return string
     */
    public function getGymId()
    {
        return $this->gym_id;
    }

    /**
     * Set 'gym_id' value
     *
     * @param string $value
     */
    public function setGymId($value = null)
    {
        $this->gym_id = $value;
    }

    /**
     * Check if 'player_lat_degrees' has a value
     *
     * @return bool
     */
    public function hasPlayerLatDegrees()
    {
        return $this->player_lat_degrees !== null;
    }

    /**
     * Get 'player_lat_degrees' value
     *
     * @return float
     */
    public function getPlayerLatDegrees()
    {
        return $this->player_lat_degrees;
    }

    /**
     * Set 'player_lat_degrees' value
     *
     * @param float $value
     */
    public function setPlayerLatDegrees($value = null)
    {
        $this->player_lat_degrees = $value;
    }

    /**
     * Check if 'player_lng_degrees' has a value
     *
     * @return bool
     */
    public function hasPlayerLngDegrees()
    {
        return $this->player_lng_degrees !== null;
    }

    /**
     * Get 'player_lng_degrees' value
     *
     * @return float
     */
    public function getPlayerLngDegrees()
    {
        return $this->player_lng_degrees;
    }

    /**
     * Set 'player_lng_degrees' value
     *
     * @param float $value
     */
    public function setPlayerLngDegrees($value = null)
    {
        $this->player_lng_degrees = $value;
    }

    /**
     * Check if 'gym_lat_degrees' has a value
     *
     * @return bool
     */
    public function hasGymLatDegrees()
    {
        return $this->gym_lat_degrees !== null;
    }

    /**
     * Get 'gym_lat_degrees' value
     *
     * @return float
     */
    public function getGymLatDegrees()
    {
        return $this->gym_lat_degrees;
    }

    /**
     * Set 'gym_lat_degrees' value
     *
     * @param float $value
     */
    public function setGymLatDegrees($value = null)
    {
        $this->gym_lat_degrees = $value;
    }

    /**
     * Check if 'gym_lng_degrees' has a value
     *
     * @return bool
     */
    public function hasGymLngDegrees()
    {
        return $this->gym_lng_degrees !== null;
    }

    /**
     * Get 'gym_lng_degrees' value
     *
     * @return float
     */
    public function getGymLngDegrees()
    {
        return $this->gym_lng_degrees;
    }

    /**
     * Set 'gym_lng_degrees' value
     *
     * @param float $value
     */
    public function setGymLngDegrees($value = null)
    {
        $this->gym_lng_degrees = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'gym_id' => null,
            'player_lat_degrees' => null,
            'player_lng_degrees' => null,
            'gym_lat_degrees' => null,
            'gym_lng_degrees' => null
        ], $values);

        $message->setGymId($values['gym_id']);
        $message->setPlayerLatDegrees($values['player_lat_degrees']);
        $message->setPlayerLngDegrees($values['player_lng_degrees']);
        $message->setGymLatDegrees($values['gym_lat_degrees']);
        $message->setGymLngDegrees($values['gym_lng_degrees']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'GymGetInfoMessage',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'gym_id',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'player_lat_degrees',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_DOUBLE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'player_lng_degrees',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_DOUBLE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'gym_lat_degrees',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_DOUBLE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'gym_lng_degrees',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_DOUBLE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->gym_id !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeString($stream, $this->gym_id);
        }

        if ($this->player_lat_degrees !== null) {
            $writer->writeVarint($stream, 17);
            $writer->writeDouble($stream, $this->player_lat_degrees);
        }

        if ($this->player_lng_degrees !== null) {
            $writer->writeVarint($stream, 25);
            $writer->writeDouble($stream, $this->player_lng_degrees);
        }

        if ($this->gym_lat_degrees !== null) {
            $writer->writeVarint($stream, 33);
            $writer->writeDouble($stream, $this->gym_lat_degrees);
        }

        if ($this->gym_lng_degrees !== null) {
            $writer->writeVarint($stream, 41);
            $writer->writeDouble($stream, $this->gym_lng_degrees);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->gym_id = $reader->readString($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 1);

                $this->player_lat_degrees = $reader->readDouble($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 1);

                $this->player_lng_degrees = $reader->readDouble($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 1);

                $this->gym_lat_degrees = $reader->readDouble($stream);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 1);

                $this->gym_lng_degrees = $reader->readDouble($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->gym_id !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->gym_id);
        }

        if ($this->player_lat_degrees !== null) {
            $size += 1;
            $size += 8;
        }

        if ($this->player_lng_degrees !== null) {
            $size += 1;
            $size += 8;
        }

        if ($this->gym_lat_degrees !== null) {
            $size += 1;
            $size += 8;
        }

        if ($this->gym_lng_degrees !== null) {
            $size += 1;
            $size += 8;
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->gym_id = null;
        $this->player_lat_degrees = null;
        $this->player_lng_degrees = null;
        $this->gym_lat_degrees = null;
        $this->gym_lng_degrees = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \POGOProtos\Networking\Requests\Messages\GymGetInfoMessage) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->gym_id = ($message->gym_id !== null) ? $message->gym_id : $this->gym_id;
        $this->player_lat_degrees = ($message->player_lat_degrees !== null) ? $message->player_lat_degrees : $this->player_lat_degrees;
        $this->player_lng_degrees = ($message->player_lng_degrees !== null) ? $message->player_lng_degrees : $this->player_lng_degrees;
        $this->gym_lat_degrees = ($message->gym_lat_degrees !== null) ? $message->gym_lat_degrees : $this->gym_lat_degrees;
        $this->gym_lng_degrees = ($message->gym_lng_degrees !== null) ? $message->gym_lng_degrees : $this->gym_lng_degrees;
    }


}

