<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/NicknamePokemonMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class NicknamePokemonMessage extends \Google\Protobuf\Internal\Message
{
    private $pokemon_id = 0;
    private $nickname = '';

    public function getPokemonId()
    {
        return $this->pokemon_id;
    }

    public function setPokemonId($var)
    {
        GPBUtil::checkUint64($var);
        $this->pokemon_id = $var;
    }

    public function getNickname()
    {
        return $this->nickname;
    }

    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0ab7010a44504f474f50726f746f732f4e6574776f726b696e672f526571" .
    "75657374732f4d657373616765732f4e69636b6e616d65506f6b656d6f6e" .
    "4d6573736167652e70726f746f1227504f474f50726f746f732e4e657477" .
    "6f726b696e672e52657175657374732e4d65737361676573223e0a164e69" .
    "636b6e616d65506f6b656d6f6e4d65737361676512120a0a706f6b656d6f" .
    "6e5f696418012001280612100a086e69636b6e616d651802200128096206" .
    "70726f746f33"
));

