<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor :
 * POGOProtos/Networking/Requests/Messages/StartGymBattleMessage.proto
 */


namespace POGOProtos\Networking\Requests\Messages;

/**
 * Protobuf message : POGOProtos.Networking.Requests.Messages.StartGymBattleMessage
 */
class StartGymBattleMessage extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * gym_id optional string = 1
     *
     * @var string
     */
    protected $gym_id = null;

    /**
     * attacking_pokemon_ids repeated fixed64 = 2
     *
     * @var \Protobuf\Collection
     */
    protected $attacking_pokemon_ids = null;

    /**
     * defending_pokemon_id optional fixed64 = 3
     *
     * @var int
     */
    protected $defending_pokemon_id = null;

    /**
     * player_latitude optional double = 4
     *
     * @var float
     */
    protected $player_latitude = null;

    /**
     * player_longitude optional double = 5
     *
     * @var float
     */
    protected $player_longitude = null;

    /**
     * Check if 'gym_id' has a value
     *
     * @return bool
     */
    public function hasGymId()
    {
        return $this->gym_id !== null;
    }

    /**
     * Get 'gym_id' value
     *
     * @return string
     */
    public function getGymId()
    {
        return $this->gym_id;
    }

    /**
     * Set 'gym_id' value
     *
     * @param string $value
     */
    public function setGymId($value = null)
    {
        $this->gym_id = $value;
    }

    /**
     * Check if 'attacking_pokemon_ids' has a value
     *
     * @return bool
     */
    public function hasAttackingPokemonIdsList()
    {
        return $this->attacking_pokemon_ids !== null;
    }

    /**
     * Get 'attacking_pokemon_ids' value
     *
     * @return \Protobuf\Collection
     */
    public function getAttackingPokemonIdsList()
    {
        return $this->attacking_pokemon_ids;
    }

    /**
     * Set 'attacking_pokemon_ids' value
     *
     * @param \Protobuf\Collection $value
     */
    public function setAttackingPokemonIdsList(\Protobuf\Collection $value = null)
    {
        $this->attacking_pokemon_ids = $value;
    }

    /**
     * Add a new element to 'attacking_pokemon_ids'
     *
     * @param int $value
     */
    public function addAttackingPokemonIds($value)
    {
        if ($this->attacking_pokemon_ids === null) {
            $this->attacking_pokemon_ids = new \Protobuf\ScalarCollection();
        }

        $this->attacking_pokemon_ids->add($value);
    }

    /**
     * Check if 'defending_pokemon_id' has a value
     *
     * @return bool
     */
    public function hasDefendingPokemonId()
    {
        return $this->defending_pokemon_id !== null;
    }

    /**
     * Get 'defending_pokemon_id' value
     *
     * @return int
     */
    public function getDefendingPokemonId()
    {
        return $this->defending_pokemon_id;
    }

    /**
     * Set 'defending_pokemon_id' value
     *
     * @param int $value
     */
    public function setDefendingPokemonId($value = null)
    {
        $this->defending_pokemon_id = $value;
    }

    /**
     * Check if 'player_latitude' has a value
     *
     * @return bool
     */
    public function hasPlayerLatitude()
    {
        return $this->player_latitude !== null;
    }

    /**
     * Get 'player_latitude' value
     *
     * @return float
     */
    public function getPlayerLatitude()
    {
        return $this->player_latitude;
    }

    /**
     * Set 'player_latitude' value
     *
     * @param float $value
     */
    public function setPlayerLatitude($value = null)
    {
        $this->player_latitude = $value;
    }

    /**
     * Check if 'player_longitude' has a value
     *
     * @return bool
     */
    public function hasPlayerLongitude()
    {
        return $this->player_longitude !== null;
    }

    /**
     * Get 'player_longitude' value
     *
     * @return float
     */
    public function getPlayerLongitude()
    {
        return $this->player_longitude;
    }

    /**
     * Set 'player_longitude' value
     *
     * @param float $value
     */
    public function setPlayerLongitude($value = null)
    {
        $this->player_longitude = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'gym_id' => null,
            'attacking_pokemon_ids' => [],
            'defending_pokemon_id' => null,
            'player_latitude' => null,
            'player_longitude' => null
        ], $values);

        $message->setGymId($values['gym_id']);
        $message->setDefendingPokemonId($values['defending_pokemon_id']);
        $message->setPlayerLatitude($values['player_latitude']);
        $message->setPlayerLongitude($values['player_longitude']);

        foreach ($values['attacking_pokemon_ids'] as $item) {
            $message->addAttackingPokemonIds($item);
        }

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'StartGymBattleMessage',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'gym_id',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'attacking_pokemon_ids',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_FIXED64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REPEATED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'defending_pokemon_id',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_FIXED64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'player_latitude',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_DOUBLE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'player_longitude',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_DOUBLE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->gym_id !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeString($stream, $this->gym_id);
        }

        if ($this->attacking_pokemon_ids !== null) {
            foreach ($this->attacking_pokemon_ids as $val) {
                $writer->writeVarint($stream, 17);
                $writer->writeFixed64($stream, $val);
            }
        }

        if ($this->defending_pokemon_id !== null) {
            $writer->writeVarint($stream, 25);
            $writer->writeFixed64($stream, $this->defending_pokemon_id);
        }

        if ($this->player_latitude !== null) {
            $writer->writeVarint($stream, 33);
            $writer->writeDouble($stream, $this->player_latitude);
        }

        if ($this->player_longitude !== null) {
            $writer->writeVarint($stream, 41);
            $writer->writeDouble($stream, $this->player_longitude);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->gym_id = $reader->readString($stream);

                continue;
            }

            if ($tag === 2) {
                $innerSize  = $reader->readVarint($stream);
                $innerLimit = $stream->tell() + $innerSize;

                if ($this->attacking_pokemon_ids === null) {
                    $this->attacking_pokemon_ids = new \Protobuf\ScalarCollection();
                }

                while ($stream->tell() < $innerLimit) {
                    $this->attacking_pokemon_ids->add($reader->readFixed64($stream));
                }

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 6);

                $this->defending_pokemon_id = $reader->readFixed64($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 1);

                $this->player_latitude = $reader->readDouble($stream);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 1);

                $this->player_longitude = $reader->readDouble($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->gym_id !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->gym_id);
        }

        if ($this->attacking_pokemon_ids !== null) {
            foreach ($this->attacking_pokemon_ids as $val) {
                $size += 1;
                $size += 8;
            }
        }

        if ($this->defending_pokemon_id !== null) {
            $size += 1;
            $size += 8;
        }

        if ($this->player_latitude !== null) {
            $size += 1;
            $size += 8;
        }

        if ($this->player_longitude !== null) {
            $size += 1;
            $size += 8;
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->gym_id = null;
        $this->attacking_pokemon_ids = null;
        $this->defending_pokemon_id = null;
        $this->player_latitude = null;
        $this->player_longitude = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \POGOProtos\Networking\Requests\Messages\StartGymBattleMessage) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->gym_id = ($message->gym_id !== null) ? $message->gym_id : $this->gym_id;
        $this->attacking_pokemon_ids = ($message->attacking_pokemon_ids !== null) ? $message->attacking_pokemon_ids : $this->attacking_pokemon_ids;
        $this->defending_pokemon_id = ($message->defending_pokemon_id !== null) ? $message->defending_pokemon_id : $this->defending_pokemon_id;
        $this->player_latitude = ($message->player_latitude !== null) ? $message->player_latitude : $this->player_latitude;
        $this->player_longitude = ($message->player_longitude !== null) ? $message->player_longitude : $this->player_longitude;
    }


}

