<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : POGOProtos/Networking/Responses/CatchPokemonResponse.proto
 */


namespace POGOProtos\Networking\Responses\CatchPokemonResponse;

/**
 * Protobuf enum :
 * POGOProtos.Networking.Responses.CatchPokemonResponse.CaptureReason
 */
class CaptureReason extends \Protobuf\Enum
{

    /**
     * UNSET = 0
     */
    const UNSET_VALUE = 0;

    /**
     * DEFAULT = 1
     */
    const DEFAULT_VALUE = 1;

    /**
     * ELEMENTAL_BADGE = 2
     */
    const ELEMENTAL_BADGE_VALUE = 2;

    /**
     * CRITICAL_CATCH = 3
     */
    const CRITICAL_CATCH_VALUE = 3;

    /**
     * @var \POGOProtos\Networking\Responses\CatchPokemonResponse\CaptureReason
     */
    protected static $UNSET = null;

    /**
     * @var \POGOProtos\Networking\Responses\CatchPokemonResponse\CaptureReason
     */
    protected static $DEFAULT = null;

    /**
     * @var \POGOProtos\Networking\Responses\CatchPokemonResponse\CaptureReason
     */
    protected static $ELEMENTAL_BADGE = null;

    /**
     * @var \POGOProtos\Networking\Responses\CatchPokemonResponse\CaptureReason
     */
    protected static $CRITICAL_CATCH = null;

    /**
     * @return \POGOProtos\Networking\Responses\CatchPokemonResponse\CaptureReason
     */
    public static function UNSET()
    {
        if (self::$UNSET !== null) {
            return self::$UNSET;
        }

        return self::$UNSET = new self('UNSET', self::UNSET_VALUE);
    }

    /**
     * @return \POGOProtos\Networking\Responses\CatchPokemonResponse\CaptureReason
     */
    public static function DEFAULT()
    {
        if (self::$DEFAULT !== null) {
            return self::$DEFAULT;
        }

        return self::$DEFAULT = new self('DEFAULT', self::DEFAULT_VALUE);
    }

    /**
     * @return \POGOProtos\Networking\Responses\CatchPokemonResponse\CaptureReason
     */
    public static function ELEMENTAL_BADGE()
    {
        if (self::$ELEMENTAL_BADGE !== null) {
            return self::$ELEMENTAL_BADGE;
        }

        return self::$ELEMENTAL_BADGE = new self('ELEMENTAL_BADGE', self::ELEMENTAL_BADGE_VALUE);
    }

    /**
     * @return \POGOProtos\Networking\Responses\CatchPokemonResponse\CaptureReason
     */
    public static function CRITICAL_CATCH()
    {
        if (self::$CRITICAL_CATCH !== null) {
            return self::$CRITICAL_CATCH;
        }

        return self::$CRITICAL_CATCH = new self('CRITICAL_CATCH', self::CRITICAL_CATCH_VALUE);
    }

    /**
     * @param int $value
     * @return \POGOProtos\Networking\Responses\CatchPokemonResponse\CaptureReason
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::UNSET();
            case 1: return self::DEFAULT();
            case 2: return self::ELEMENTAL_BADGE();
            case 3: return self::CRITICAL_CATCH();
            default: return null;
        }
    }


}

