<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor :
 * POGOProtos/Networking/Platform/Responses/BuyItemPokeCoinsResponse.proto
 */


namespace POGOProtos\Networking\Platform\Responses\BuyItemPokeCoinsResponse;

/**
 * Protobuf enum :
 * POGOProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponse.Status
 */
class Status extends \Protobuf\Enum
{

    /**
     * UNKNOWN = 0
     */
    const UNKNOWN_VALUE = 0;

    /**
     * SUCCESS = 1
     */
    const SUCCESS_VALUE = 1;

    /**
     * NOT_ENOUGH_POKECOINS = 3
     */
    const NOT_ENOUGH_POKECOINS_VALUE = 3;

    /**
     * @var \POGOProtos\Networking\Platform\Responses\BuyItemPokeCoinsResponse\Status
     */
    protected static $UNKNOWN = null;

    /**
     * @var \POGOProtos\Networking\Platform\Responses\BuyItemPokeCoinsResponse\Status
     */
    protected static $SUCCESS = null;

    /**
     * @var \POGOProtos\Networking\Platform\Responses\BuyItemPokeCoinsResponse\Status
     */
    protected static $NOT_ENOUGH_POKECOINS = null;

    /**
     * @return \POGOProtos\Networking\Platform\Responses\BuyItemPokeCoinsResponse\Status
     */
    public static function UNKNOWN()
    {
        if (self::$UNKNOWN !== null) {
            return self::$UNKNOWN;
        }

        return self::$UNKNOWN = new self('UNKNOWN', self::UNKNOWN_VALUE);
    }

    /**
     * @return \POGOProtos\Networking\Platform\Responses\BuyItemPokeCoinsResponse\Status
     */
    public static function SUCCESS()
    {
        if (self::$SUCCESS !== null) {
            return self::$SUCCESS;
        }

        return self::$SUCCESS = new self('SUCCESS', self::SUCCESS_VALUE);
    }

    /**
     * @return \POGOProtos\Networking\Platform\Responses\BuyItemPokeCoinsResponse\Status
     */
    public static function NOT_ENOUGH_POKECOINS()
    {
        if (self::$NOT_ENOUGH_POKECOINS !== null) {
            return self::$NOT_ENOUGH_POKECOINS;
        }

        return self::$NOT_ENOUGH_POKECOINS = new self('NOT_ENOUGH_POKECOINS', self::NOT_ENOUGH_POKECOINS_VALUE);
    }

    /**
     * @param int $value
     * @return \POGOProtos\Networking\Platform\Responses\BuyItemPokeCoinsResponse\Status
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::UNKNOWN();
            case 1: return self::SUCCESS();
            case 3: return self::NOT_ENOUGH_POKECOINS();
            default: return null;
        }
    }


}

