<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : POGOProtos/Inventory/Item/ItemId.proto
 */


namespace POGOProtos\Inventory\Item;

/**
 * Protobuf enum : POGOProtos.Inventory.Item.ItemId
 */
class ItemId extends \Protobuf\Enum
{

    /**
     * ITEM_UNKNOWN = 0
     */
    const ITEM_UNKNOWN_VALUE = 0;

    /**
     * ITEM_POKE_BALL = 1
     */
    const ITEM_POKE_BALL_VALUE = 1;

    /**
     * ITEM_GREAT_BALL = 2
     */
    const ITEM_GREAT_BALL_VALUE = 2;

    /**
     * ITEM_ULTRA_BALL = 3
     */
    const ITEM_ULTRA_BALL_VALUE = 3;

    /**
     * ITEM_MASTER_BALL = 4
     */
    const ITEM_MASTER_BALL_VALUE = 4;

    /**
     * ITEM_POTION = 101
     */
    const ITEM_POTION_VALUE = 101;

    /**
     * ITEM_SUPER_POTION = 102
     */
    const ITEM_SUPER_POTION_VALUE = 102;

    /**
     * ITEM_HYPER_POTION = 103
     */
    const ITEM_HYPER_POTION_VALUE = 103;

    /**
     * ITEM_MAX_POTION = 104
     */
    const ITEM_MAX_POTION_VALUE = 104;

    /**
     * ITEM_REVIVE = 201
     */
    const ITEM_REVIVE_VALUE = 201;

    /**
     * ITEM_MAX_REVIVE = 202
     */
    const ITEM_MAX_REVIVE_VALUE = 202;

    /**
     * ITEM_LUCKY_EGG = 301
     */
    const ITEM_LUCKY_EGG_VALUE = 301;

    /**
     * ITEM_INCENSE_ORDINARY = 401
     */
    const ITEM_INCENSE_ORDINARY_VALUE = 401;

    /**
     * ITEM_INCENSE_SPICY = 402
     */
    const ITEM_INCENSE_SPICY_VALUE = 402;

    /**
     * ITEM_INCENSE_COOL = 403
     */
    const ITEM_INCENSE_COOL_VALUE = 403;

    /**
     * ITEM_INCENSE_FLORAL = 404
     */
    const ITEM_INCENSE_FLORAL_VALUE = 404;

    /**
     * ITEM_TROY_DISK = 501
     */
    const ITEM_TROY_DISK_VALUE = 501;

    /**
     * ITEM_X_ATTACK = 602
     */
    const ITEM_X_ATTACK_VALUE = 602;

    /**
     * ITEM_X_DEFENSE = 603
     */
    const ITEM_X_DEFENSE_VALUE = 603;

    /**
     * ITEM_X_MIRACLE = 604
     */
    const ITEM_X_MIRACLE_VALUE = 604;

    /**
     * ITEM_RAZZ_BERRY = 701
     */
    const ITEM_RAZZ_BERRY_VALUE = 701;

    /**
     * ITEM_BLUK_BERRY = 702
     */
    const ITEM_BLUK_BERRY_VALUE = 702;

    /**
     * ITEM_NANAB_BERRY = 703
     */
    const ITEM_NANAB_BERRY_VALUE = 703;

    /**
     * ITEM_WEPAR_BERRY = 704
     */
    const ITEM_WEPAR_BERRY_VALUE = 704;

    /**
     * ITEM_PINAP_BERRY = 705
     */
    const ITEM_PINAP_BERRY_VALUE = 705;

    /**
     * ITEM_SPECIAL_CAMERA = 801
     */
    const ITEM_SPECIAL_CAMERA_VALUE = 801;

    /**
     * ITEM_INCUBATOR_BASIC_UNLIMITED = 901
     */
    const ITEM_INCUBATOR_BASIC_UNLIMITED_VALUE = 901;

    /**
     * ITEM_INCUBATOR_BASIC = 902
     */
    const ITEM_INCUBATOR_BASIC_VALUE = 902;

    /**
     * ITEM_POKEMON_STORAGE_UPGRADE = 1001
     */
    const ITEM_POKEMON_STORAGE_UPGRADE_VALUE = 1001;

    /**
     * ITEM_ITEM_STORAGE_UPGRADE = 1002
     */
    const ITEM_ITEM_STORAGE_UPGRADE_VALUE = 1002;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_UNKNOWN = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_POKE_BALL = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_GREAT_BALL = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_ULTRA_BALL = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_MASTER_BALL = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_POTION = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_SUPER_POTION = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_HYPER_POTION = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_MAX_POTION = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_REVIVE = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_MAX_REVIVE = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_LUCKY_EGG = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_INCENSE_ORDINARY = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_INCENSE_SPICY = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_INCENSE_COOL = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_INCENSE_FLORAL = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_TROY_DISK = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_X_ATTACK = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_X_DEFENSE = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_X_MIRACLE = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_RAZZ_BERRY = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_BLUK_BERRY = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_NANAB_BERRY = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_WEPAR_BERRY = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_PINAP_BERRY = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_SPECIAL_CAMERA = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_INCUBATOR_BASIC_UNLIMITED = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_INCUBATOR_BASIC = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_POKEMON_STORAGE_UPGRADE = null;

    /**
     * @var \POGOProtos\Inventory\Item\ItemId
     */
    protected static $ITEM_ITEM_STORAGE_UPGRADE = null;

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_UNKNOWN()
    {
        if (self::$ITEM_UNKNOWN !== null) {
            return self::$ITEM_UNKNOWN;
        }

        return self::$ITEM_UNKNOWN = new self('ITEM_UNKNOWN', self::ITEM_UNKNOWN_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_POKE_BALL()
    {
        if (self::$ITEM_POKE_BALL !== null) {
            return self::$ITEM_POKE_BALL;
        }

        return self::$ITEM_POKE_BALL = new self('ITEM_POKE_BALL', self::ITEM_POKE_BALL_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_GREAT_BALL()
    {
        if (self::$ITEM_GREAT_BALL !== null) {
            return self::$ITEM_GREAT_BALL;
        }

        return self::$ITEM_GREAT_BALL = new self('ITEM_GREAT_BALL', self::ITEM_GREAT_BALL_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_ULTRA_BALL()
    {
        if (self::$ITEM_ULTRA_BALL !== null) {
            return self::$ITEM_ULTRA_BALL;
        }

        return self::$ITEM_ULTRA_BALL = new self('ITEM_ULTRA_BALL', self::ITEM_ULTRA_BALL_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_MASTER_BALL()
    {
        if (self::$ITEM_MASTER_BALL !== null) {
            return self::$ITEM_MASTER_BALL;
        }

        return self::$ITEM_MASTER_BALL = new self('ITEM_MASTER_BALL', self::ITEM_MASTER_BALL_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_POTION()
    {
        if (self::$ITEM_POTION !== null) {
            return self::$ITEM_POTION;
        }

        return self::$ITEM_POTION = new self('ITEM_POTION', self::ITEM_POTION_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_SUPER_POTION()
    {
        if (self::$ITEM_SUPER_POTION !== null) {
            return self::$ITEM_SUPER_POTION;
        }

        return self::$ITEM_SUPER_POTION = new self('ITEM_SUPER_POTION', self::ITEM_SUPER_POTION_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_HYPER_POTION()
    {
        if (self::$ITEM_HYPER_POTION !== null) {
            return self::$ITEM_HYPER_POTION;
        }

        return self::$ITEM_HYPER_POTION = new self('ITEM_HYPER_POTION', self::ITEM_HYPER_POTION_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_MAX_POTION()
    {
        if (self::$ITEM_MAX_POTION !== null) {
            return self::$ITEM_MAX_POTION;
        }

        return self::$ITEM_MAX_POTION = new self('ITEM_MAX_POTION', self::ITEM_MAX_POTION_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_REVIVE()
    {
        if (self::$ITEM_REVIVE !== null) {
            return self::$ITEM_REVIVE;
        }

        return self::$ITEM_REVIVE = new self('ITEM_REVIVE', self::ITEM_REVIVE_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_MAX_REVIVE()
    {
        if (self::$ITEM_MAX_REVIVE !== null) {
            return self::$ITEM_MAX_REVIVE;
        }

        return self::$ITEM_MAX_REVIVE = new self('ITEM_MAX_REVIVE', self::ITEM_MAX_REVIVE_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_LUCKY_EGG()
    {
        if (self::$ITEM_LUCKY_EGG !== null) {
            return self::$ITEM_LUCKY_EGG;
        }

        return self::$ITEM_LUCKY_EGG = new self('ITEM_LUCKY_EGG', self::ITEM_LUCKY_EGG_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_INCENSE_ORDINARY()
    {
        if (self::$ITEM_INCENSE_ORDINARY !== null) {
            return self::$ITEM_INCENSE_ORDINARY;
        }

        return self::$ITEM_INCENSE_ORDINARY = new self('ITEM_INCENSE_ORDINARY', self::ITEM_INCENSE_ORDINARY_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_INCENSE_SPICY()
    {
        if (self::$ITEM_INCENSE_SPICY !== null) {
            return self::$ITEM_INCENSE_SPICY;
        }

        return self::$ITEM_INCENSE_SPICY = new self('ITEM_INCENSE_SPICY', self::ITEM_INCENSE_SPICY_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_INCENSE_COOL()
    {
        if (self::$ITEM_INCENSE_COOL !== null) {
            return self::$ITEM_INCENSE_COOL;
        }

        return self::$ITEM_INCENSE_COOL = new self('ITEM_INCENSE_COOL', self::ITEM_INCENSE_COOL_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_INCENSE_FLORAL()
    {
        if (self::$ITEM_INCENSE_FLORAL !== null) {
            return self::$ITEM_INCENSE_FLORAL;
        }

        return self::$ITEM_INCENSE_FLORAL = new self('ITEM_INCENSE_FLORAL', self::ITEM_INCENSE_FLORAL_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_TROY_DISK()
    {
        if (self::$ITEM_TROY_DISK !== null) {
            return self::$ITEM_TROY_DISK;
        }

        return self::$ITEM_TROY_DISK = new self('ITEM_TROY_DISK', self::ITEM_TROY_DISK_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_X_ATTACK()
    {
        if (self::$ITEM_X_ATTACK !== null) {
            return self::$ITEM_X_ATTACK;
        }

        return self::$ITEM_X_ATTACK = new self('ITEM_X_ATTACK', self::ITEM_X_ATTACK_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_X_DEFENSE()
    {
        if (self::$ITEM_X_DEFENSE !== null) {
            return self::$ITEM_X_DEFENSE;
        }

        return self::$ITEM_X_DEFENSE = new self('ITEM_X_DEFENSE', self::ITEM_X_DEFENSE_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_X_MIRACLE()
    {
        if (self::$ITEM_X_MIRACLE !== null) {
            return self::$ITEM_X_MIRACLE;
        }

        return self::$ITEM_X_MIRACLE = new self('ITEM_X_MIRACLE', self::ITEM_X_MIRACLE_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_RAZZ_BERRY()
    {
        if (self::$ITEM_RAZZ_BERRY !== null) {
            return self::$ITEM_RAZZ_BERRY;
        }

        return self::$ITEM_RAZZ_BERRY = new self('ITEM_RAZZ_BERRY', self::ITEM_RAZZ_BERRY_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_BLUK_BERRY()
    {
        if (self::$ITEM_BLUK_BERRY !== null) {
            return self::$ITEM_BLUK_BERRY;
        }

        return self::$ITEM_BLUK_BERRY = new self('ITEM_BLUK_BERRY', self::ITEM_BLUK_BERRY_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_NANAB_BERRY()
    {
        if (self::$ITEM_NANAB_BERRY !== null) {
            return self::$ITEM_NANAB_BERRY;
        }

        return self::$ITEM_NANAB_BERRY = new self('ITEM_NANAB_BERRY', self::ITEM_NANAB_BERRY_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_WEPAR_BERRY()
    {
        if (self::$ITEM_WEPAR_BERRY !== null) {
            return self::$ITEM_WEPAR_BERRY;
        }

        return self::$ITEM_WEPAR_BERRY = new self('ITEM_WEPAR_BERRY', self::ITEM_WEPAR_BERRY_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_PINAP_BERRY()
    {
        if (self::$ITEM_PINAP_BERRY !== null) {
            return self::$ITEM_PINAP_BERRY;
        }

        return self::$ITEM_PINAP_BERRY = new self('ITEM_PINAP_BERRY', self::ITEM_PINAP_BERRY_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_SPECIAL_CAMERA()
    {
        if (self::$ITEM_SPECIAL_CAMERA !== null) {
            return self::$ITEM_SPECIAL_CAMERA;
        }

        return self::$ITEM_SPECIAL_CAMERA = new self('ITEM_SPECIAL_CAMERA', self::ITEM_SPECIAL_CAMERA_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_INCUBATOR_BASIC_UNLIMITED()
    {
        if (self::$ITEM_INCUBATOR_BASIC_UNLIMITED !== null) {
            return self::$ITEM_INCUBATOR_BASIC_UNLIMITED;
        }

        return self::$ITEM_INCUBATOR_BASIC_UNLIMITED = new self('ITEM_INCUBATOR_BASIC_UNLIMITED', self::ITEM_INCUBATOR_BASIC_UNLIMITED_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_INCUBATOR_BASIC()
    {
        if (self::$ITEM_INCUBATOR_BASIC !== null) {
            return self::$ITEM_INCUBATOR_BASIC;
        }

        return self::$ITEM_INCUBATOR_BASIC = new self('ITEM_INCUBATOR_BASIC', self::ITEM_INCUBATOR_BASIC_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_POKEMON_STORAGE_UPGRADE()
    {
        if (self::$ITEM_POKEMON_STORAGE_UPGRADE !== null) {
            return self::$ITEM_POKEMON_STORAGE_UPGRADE;
        }

        return self::$ITEM_POKEMON_STORAGE_UPGRADE = new self('ITEM_POKEMON_STORAGE_UPGRADE', self::ITEM_POKEMON_STORAGE_UPGRADE_VALUE);
    }

    /**
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function ITEM_ITEM_STORAGE_UPGRADE()
    {
        if (self::$ITEM_ITEM_STORAGE_UPGRADE !== null) {
            return self::$ITEM_ITEM_STORAGE_UPGRADE;
        }

        return self::$ITEM_ITEM_STORAGE_UPGRADE = new self('ITEM_ITEM_STORAGE_UPGRADE', self::ITEM_ITEM_STORAGE_UPGRADE_VALUE);
    }

    /**
     * @param int $value
     * @return \POGOProtos\Inventory\Item\ItemId
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::ITEM_UNKNOWN();
            case 1: return self::ITEM_POKE_BALL();
            case 2: return self::ITEM_GREAT_BALL();
            case 3: return self::ITEM_ULTRA_BALL();
            case 4: return self::ITEM_MASTER_BALL();
            case 101: return self::ITEM_POTION();
            case 102: return self::ITEM_SUPER_POTION();
            case 103: return self::ITEM_HYPER_POTION();
            case 104: return self::ITEM_MAX_POTION();
            case 201: return self::ITEM_REVIVE();
            case 202: return self::ITEM_MAX_REVIVE();
            case 301: return self::ITEM_LUCKY_EGG();
            case 401: return self::ITEM_INCENSE_ORDINARY();
            case 402: return self::ITEM_INCENSE_SPICY();
            case 403: return self::ITEM_INCENSE_COOL();
            case 404: return self::ITEM_INCENSE_FLORAL();
            case 501: return self::ITEM_TROY_DISK();
            case 602: return self::ITEM_X_ATTACK();
            case 603: return self::ITEM_X_DEFENSE();
            case 604: return self::ITEM_X_MIRACLE();
            case 701: return self::ITEM_RAZZ_BERRY();
            case 702: return self::ITEM_BLUK_BERRY();
            case 703: return self::ITEM_NANAB_BERRY();
            case 704: return self::ITEM_WEPAR_BERRY();
            case 705: return self::ITEM_PINAP_BERRY();
            case 801: return self::ITEM_SPECIAL_CAMERA();
            case 901: return self::ITEM_INCUBATOR_BASIC_UNLIMITED();
            case 902: return self::ITEM_INCUBATOR_BASIC();
            case 1001: return self::ITEM_POKEMON_STORAGE_UPGRADE();
            case 1002: return self::ITEM_ITEM_STORAGE_UPGRADE();
            default: return null;
        }
    }


}

