<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : POGOProtos/Settings/Master/Quest/DailyQuestSettings.proto
 */


namespace POGOProtos\Settings\Master\Quest;

/**
 * Protobuf message : POGOProtos.Settings.Master.Quest.DailyQuestSettings
 */
class DailyQuestSettings extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * buckets_per_day optional int32 = 1
     *
     * @var int
     */
    protected $buckets_per_day = null;

    /**
     * streak_length optional int32 = 2
     *
     * @var int
     */
    protected $streak_length = null;

    /**
     * bonus_multiplier optional float = 3
     *
     * @var float
     */
    protected $bonus_multiplier = null;

    /**
     * streak_bonus_multiplier optional float = 4
     *
     * @var float
     */
    protected $streak_bonus_multiplier = null;

    /**
     * Check if 'buckets_per_day' has a value
     *
     * @return bool
     */
    public function hasBucketsPerDay()
    {
        return $this->buckets_per_day !== null;
    }

    /**
     * Get 'buckets_per_day' value
     *
     * @return int
     */
    public function getBucketsPerDay()
    {
        return $this->buckets_per_day;
    }

    /**
     * Set 'buckets_per_day' value
     *
     * @param int $value
     */
    public function setBucketsPerDay($value = null)
    {
        $this->buckets_per_day = $value;
    }

    /**
     * Check if 'streak_length' has a value
     *
     * @return bool
     */
    public function hasStreakLength()
    {
        return $this->streak_length !== null;
    }

    /**
     * Get 'streak_length' value
     *
     * @return int
     */
    public function getStreakLength()
    {
        return $this->streak_length;
    }

    /**
     * Set 'streak_length' value
     *
     * @param int $value
     */
    public function setStreakLength($value = null)
    {
        $this->streak_length = $value;
    }

    /**
     * Check if 'bonus_multiplier' has a value
     *
     * @return bool
     */
    public function hasBonusMultiplier()
    {
        return $this->bonus_multiplier !== null;
    }

    /**
     * Get 'bonus_multiplier' value
     *
     * @return float
     */
    public function getBonusMultiplier()
    {
        return $this->bonus_multiplier;
    }

    /**
     * Set 'bonus_multiplier' value
     *
     * @param float $value
     */
    public function setBonusMultiplier($value = null)
    {
        $this->bonus_multiplier = $value;
    }

    /**
     * Check if 'streak_bonus_multiplier' has a value
     *
     * @return bool
     */
    public function hasStreakBonusMultiplier()
    {
        return $this->streak_bonus_multiplier !== null;
    }

    /**
     * Get 'streak_bonus_multiplier' value
     *
     * @return float
     */
    public function getStreakBonusMultiplier()
    {
        return $this->streak_bonus_multiplier;
    }

    /**
     * Set 'streak_bonus_multiplier' value
     *
     * @param float $value
     */
    public function setStreakBonusMultiplier($value = null)
    {
        $this->streak_bonus_multiplier = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'buckets_per_day' => null,
            'streak_length' => null,
            'bonus_multiplier' => null,
            'streak_bonus_multiplier' => null
        ], $values);

        $message->setBucketsPerDay($values['buckets_per_day']);
        $message->setStreakLength($values['streak_length']);
        $message->setBonusMultiplier($values['bonus_multiplier']);
        $message->setStreakBonusMultiplier($values['streak_bonus_multiplier']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'DailyQuestSettings',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'buckets_per_day',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'streak_length',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'bonus_multiplier',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_FLOAT(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'streak_bonus_multiplier',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_FLOAT(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->buckets_per_day !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->buckets_per_day);
        }

        if ($this->streak_length !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->streak_length);
        }

        if ($this->bonus_multiplier !== null) {
            $writer->writeVarint($stream, 29);
            $writer->writeFloat($stream, $this->bonus_multiplier);
        }

        if ($this->streak_bonus_multiplier !== null) {
            $writer->writeVarint($stream, 37);
            $writer->writeFloat($stream, $this->streak_bonus_multiplier);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->buckets_per_day = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->streak_length = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 2);

                $this->bonus_multiplier = $reader->readFloat($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 2);

                $this->streak_bonus_multiplier = $reader->readFloat($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->buckets_per_day !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->buckets_per_day);
        }

        if ($this->streak_length !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->streak_length);
        }

        if ($this->bonus_multiplier !== null) {
            $size += 1;
            $size += 4;
        }

        if ($this->streak_bonus_multiplier !== null) {
            $size += 1;
            $size += 4;
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->buckets_per_day = null;
        $this->streak_length = null;
        $this->bonus_multiplier = null;
        $this->streak_bonus_multiplier = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \POGOProtos\Settings\Master\Quest\DailyQuestSettings) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->buckets_per_day = ($message->buckets_per_day !== null) ? $message->buckets_per_day : $this->buckets_per_day;
        $this->streak_length = ($message->streak_length !== null) ? $message->streak_length : $this->streak_length;
        $this->bonus_multiplier = ($message->bonus_multiplier !== null) ? $message->bonus_multiplier : $this->bonus_multiplier;
        $this->streak_bonus_multiplier = ($message->streak_bonus_multiplier !== null) ? $message->streak_bonus_multiplier : $this->streak_bonus_multiplier;
    }


}

